cobaltcore-dev/cortex

- internal/db/db.go
- internal/db/migrations.go
- internal/db/migrations/001_add_openstack_servers_flavorid.sql
- internal/db/migrations_test.go
Before, starting with a clean DB would result in a crash.
Now the service properly tracks which migrations were
executed and if the database is fresh.
> Fix migration on clean service startup

- .github/workflows/vernemq.yaml
- helm/cortex/values.yaml
Adds build pipeline for: https://github.com/orgs/cobaltcore-dev/packages/container/package/vernemq
Also sets the vernemq docker image to ghcr.io/cobaltcore-dev/vernemq.
Needed to conform to the VerneMQ EULA.
> Add vernemq pipeline and use cobaltcore-dev/vernemq image

- Tiltfile
When freshly cloned, the repository won't have Chart.lock files which results in Tilt not starting properly. This is handled by Tilt now.
> Add helm dep update to Tiltfile

- internal/conf/yaml.go
- internal/scheduler/monitor.go
- internal/scheduler/pipeline.go
- internal/scheduler/validation.go
- internal/scheduler/validation_test.go
- Add step validator as wrapper, similar to step monitor
- Move general logging out of step monitor
- Enable all validations by default, but can be disabled through config
- No generics in step monitor
> Validate same host number in and out for weighers

- .golangci.yaml
- Tiltfile
- helm/cortex/Chart.yaml
- helm/cortex/templates/cli.yaml
- internal/commands/checks/checks.go
- main.go
This pull request adds a small pod to the Cortex helm chart, which can be used to perform commands, such as end-to-end tests. This pod will have access to the database and also the Cortex configuration, so that it can make OpenStack calls, making the implementation of e2e tests significantly easier. In our deployment pipeline, we can use the new pod to run `kubectl exec -it cortex-cli -- /usr/bin/cortex checks` to execute the tests. This tooling was also added to the Tilt setup, with a new command "Run E2E Tests".
> Add end-to-end tests

- go.mod
- go.sum
- helm/cortex/templates/_conf.yaml.tpl
- helm/cortex/templates/configmap.yaml
- internal/conf/conf.go
- internal/conf/conf_test.go
- internal/conf/opts.go
- internal/conf/opts_test.go
- internal/conf/validation.go
- internal/conf/validation_test.go
- internal/features/plugins/base.go
- internal/features/plugins/base_test.go
- internal/features/plugins/kvm/node_exporter_host_cpu_usage_test.go
- internal/features/plugins/kvm/node_exporter_host_memory_active_test.go
- internal/features/plugins/shared/flavor_host_space_test.go
- internal/features/plugins/vmware/vrops_hostsystem_contention_test.go
- internal/features/plugins/vmware/vrops_hostsystem_resolver_test.go
- internal/features/plugins/vmware/vrops_project_noisiness_test.go
- internal/scheduler/plugins/base.go
- internal/scheduler/plugins/base_test.go
- internal/scheduler/plugins/kvm/avoid_overloaded_hosts_cpu.go
- internal/scheduler/plugins/kvm/avoid_overloaded_hosts_cpu_test.go
- internal/scheduler/plugins/kvm/avoid_overloaded_hosts_memory.go
- internal/scheduler/plugins/kvm/avoid_overloaded_hosts_memory_test.go
- internal/scheduler/plugins/shared/flavor_binpacking.go
- internal/scheduler/plugins/shared/flavor_binpacking_test.go
- internal/scheduler/plugins/vmware/anti_affinity_noisy_projects.go
- internal/scheduler/plugins/vmware/anti_affinity_noisy_projects_test.go
- internal/scheduler/plugins/vmware/avoid_contended_hosts.go
- internal/scheduler/plugins/vmware/avoid_contended_hosts_test.go
`gopkg.in/yaml.v3` was archived on the 1st of April 2025. This pull request removes the direct dependency, and instead uses the json parsing built into golang for config handling. The config will now be serialized to json before it is passed to the services.
> Remove archived gopkg.in/yaml.v3 dependency

- internal/scheduler/monitor.go
- internal/scheduler/monitor_test.go
- internal/scheduler/validation_test.go
- testlib/monitoring/mock.go
- testlib/scheduler/plugins/interface.go
This PR fixes an issue where the step monitor calculates the number of reorderings based on the `hosts` list provided by Nova, which may not necessarily be sorted by the hosts' weights. Now, we compare the input and output weights correctly.
> Test step monitor run function and fix found bug

- internal/scheduler/monitor.go
- internal/scheduler/monitor_test.go
This pr adds KPIs to not only measure how many hosts were re-ordered in the scheduling pipeline, but also to measure how high the impact of this re-ordering was.
> Improve scheduler KPIs for host reorderings

- .github/workflows/test.yaml
- internal/db/db.go
- internal/features/pipeline_test.go
- internal/mqtt/mqtt.go
- internal/mqtt/mqtt_test.go
- main.go
- testlib/mqtt/containers/vernemq.go
This should avoid any services dangling around without an active connection to either.
> Fail hard on disconnects from mqtt and postgres

- Tiltfile
- helm/cortex/templates/migrations.yaml
- helm/cortex/values.yaml
- main.go
Before, every service would perform its own migrations. Now, this is a separate kubernetes job that gets executed before the kubernetes templates are applied.
> Execute db migrations as pre-upgrade hook

- helm/cortex/values.yaml
- internal/extractor/monitor.go
- internal/extractor/pipeline.go
- internal/extractor/plugins/shared/vm_life_span.go
- internal/extractor/plugins/shared/vm_life_span.sql
- internal/extractor/plugins/shared/vm_life_span_test.go
- internal/kpis/plugins/shared/host_utilization.go
- internal/kpis/plugins/shared/vm_life_span.go
- internal/kpis/plugins/shared/vm_life_span_test.go
- internal/kpis/plugins/shared/vm_migration_statistics.go
- internal/kpis/plugins/vmware/host_contention.go
- internal/kpis/plugins/vmware/project_noisiness.go
- internal/tools/histogram.go
- internal/tools/histogram_test.go
This PR moves the histogram logic of the vm_life_span kpi to the corresponding extractor, reducing the number of DB rows from n_servers (incl. deleted ones) to n_flavors * n_buckets.
> Reduce number of features calculated by vm_life_span extractor

- helm/cortex/values.yaml
- internal/kpis/pipeline.go
- internal/kpis/plugins/shared/host_total_capacity.go
- internal/kpis/plugins/shared/host_total_capacity_test.go
This PR introduces the KPI `cortex_host_total_capacity_per_host` to visualize the total capacity (CPU, RAM, Disk) of each host over time. This enhancement addresses an issue observed when a hypervisor server was physically shut down, causing the cluster’s total RAM capacity to be halved. Since neither Nova nor Placement performs automatic balancing, the VMs remain assigned to the cluster—even when they are in the `SHUTOFF` state. In OpenStack, VMs in `SHUTOFF` status continue to consume resources. As a result, Placement may report an inflated utilization value in such scenarios.
> Added host_total_capacity_kpi

- Tiltfile
- helm/cortex-postgres/Chart.lock
- helm/cortex-postgres/Chart.yaml
- helm/cortex-postgres/files/post-upgrade.sh
- helm/cortex-postgres/files/pre-upgrade.sh
- helm/cortex-postgres/templates/.gitkeep
- helm/cortex-postgres/templates/job.yaml
- helm/cortex-postgres/templates/rbac.yaml
- helm/cortex-postgres/values.yaml
By default, the bitnami postgres chart doesn't support major version upgrades without manual intervention. This PR automates the process. 
**Note: helm reinstall is needed to make this work initially, as the volume mounts of the scripts into the postgres container are initially not present.**
> Extend bitnami postgres chart to support major version upgrades

- helm/cortex-postgres/Chart.lock
- helm/cortex-postgres/Chart.yaml
- helm/cortex/Chart.yaml
This is required since our services are currently running 15.5.27 in prod regions. We need to rollout the new jobs with this version *once* and can then upgrade. I missed that in the last release.
> Release cortex-postgres 0.3.0 to roll jobs into deployments

- helm/cortex-postgres/Chart.lock
- helm/cortex-postgres/Chart.yaml
After the temporary downgrade, the deployments now support upgrading.
> Release cortex-postgres v0.3.1 to re-introduce postgres upgrade

- internal/scheduler/manila/pipeline.go
- internal/scheduler/nova/pipeline.go
- internal/scheduler/pipeline.go
- internal/scheduler/pipeline_test.go
Currently if we pass multiple steps with the same name but different steps, the init function will be called twice on the same step, leading to only one being initialized and executed. This PR adds a test for this specific condition and fixes the issue.
> Fix multiple aliases for same step overriding config

- cortex.secrets.example.yaml
- helm/cortex/templates/cli.yaml
- helm/cortex/templates/deployment.yaml
- helm/cortex/templates/migrations.yaml
- helm/cortex/templates/secret.yaml
- helm/cortex/values.yaml
- internal/conf/conf.go
- internal/conf/conf_test.go
- internal/conf/validation_test.go
Improve access control to passwords -> people without access to kubernetes secrets can still see configmap using RBAC.
> Load secrets through kubernetes secret instead of configmap

- internal/scheduler/nova/api/http/api.go
- internal/scheduler/nova/api/http/api_test.go
See https://github.com/sapcc/nova/pull/570
This is to have a 2nd safety in place, and so we don't forget that it's unsupported.
> Don't place ironic flavors

- internal/conf/conf.go
- internal/scheduler/manila/pipeline.go
- internal/scheduler/nova/pipeline.go
- internal/scheduler/nova/pipeline_test.go
- internal/scheduler/pipeline.go
- internal/scheduler/pipeline_test.go
This is useful to compare our own filters with nova filters.
Usage to enable this feature for local debugging:
```
cortex-core:
conf:
scheduler:
nova:
preselectAllHosts: true
```
> Add premodifier for pipeline to preselect all nova hosts if needed

- internal/extractor/plugins/kvm/node_exporter_host_cpu_usage_test.go
- internal/extractor/plugins/kvm/node_exporter_host_memory_active_test.go
- internal/extractor/plugins/sap/host_details_test.go
- internal/extractor/plugins/shared/vm_host_residency_test.go
- internal/extractor/plugins/shared/vm_life_span_test.go
- internal/extractor/plugins/vmware/vrops_hostsystem_contention_long_term_test.go
- internal/extractor/plugins/vmware/vrops_hostsystem_contention_short_term_test.go
- internal/extractor/plugins/vmware/vrops_hostsystem_resolver_test.go
- internal/extractor/plugins/vmware/vrops_project_noisiness_test.go
- internal/kpis/plugins/netapp/storage_pool_cpu_test.go
- internal/kpis/plugins/shared/vm_life_span_test.go
- internal/kpis/plugins/shared/vm_migration_statistics_test.go
- internal/kpis/plugins/vmware/host_contention_test.go
- internal/kpis/plugins/vmware/project_noisiness_test.go
- internal/scheduler/manila/plugins/netapp/cpu_usage_balancing_test.go
- internal/scheduler/nova/plugins/kvm/avoid_overloaded_hosts_cpu_test.go
- internal/scheduler/nova/plugins/kvm/avoid_overloaded_hosts_memory_test.go
- internal/scheduler/nova/plugins/vmware/anti_affinity_noisy_projects_test.go
- internal/scheduler/nova/plugins/vmware/avoid_long_term_contended_hosts_test.go
- internal/scheduler/nova/plugins/vmware/avoid_short_term_contended_hosts_test.go
This PR replaces all occurrences of plain table names in test cases with proper `Insert()` calls or `TableName()` method calls in SQL query strings. This ensures better maintainability and consistency across the codebase. This will help catch cases where SQL queries use outdated table names when table structures are modified
> [!NOTE]
> The Manila storage pool CPU usage test was fixed in PR #240 to avoid merge conflicts.
> Replace plain table names usage in sql queries

- helm/bundles/cortex-nova/values.yaml
- internal/extractor/pipeline.go
- internal/extractor/plugins/shared/host_pinned_project_test.go
- internal/extractor/plugins/shared/host_pinned_projects.go
- internal/extractor/plugins/shared/host_pinned_projects.sql
Open questions:
- can we just ignore aggregates with `filter_tenant_id` but without any `hosts` assigned to them
> Feature extractor for pinned projects

- .github/renovate.json
- .github/workflows/checks.yaml
- .github/workflows/ci.yaml
- .github/workflows/codeql.yaml
- .github/workflows/test.yaml
- Dockerfile
- Dockerfile.kubebuilder
- go.mod
- reservations/api/go.mod
- reservations/go.mod
- shell.nix
- Upgrade go to `1.25`
- Adjusted renovate constraints to go `1.25.x`
- Replaced `go-version` with `go-version-file` in `go-setup-action` (See: https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file)
---
- The workflows have been already upgraded to `1.25.x` via renovate PRs. If we don't want that we should add a packageRule for this as well. Example:
```js
{
"matchManagers": ["github-actions"],
"matchPackageNames": ["actions/setup-go"],
"allowedVersions": "1.25.x"
},
```
> Update Go version to 1.25

- internal/scheduler/nova/plugins/shared/filter_has_enough_capacity.go
- internal/scheduler/nova/plugins/shared/filter_has_enough_capacity_test.go
- reservations/internal/commitments/client.go
- reservations/internal/commitments/client_test.go
- reservations/internal/commitments/messages.go
- reservations/internal/commitments/messages_test.go
- reservations/internal/commitments/syncer.go
- reservations/internal/commitments/syncer_test.go
This implements the handover between limes + nova and cortex so that vms are slotted and used commitments no longer reserved.
- The reservations operator now looks for existing virtual machines of projects that have a commitment. It checks if this commitment matches the virtual machine(s) and subtract the current usage from the space we still need to reserve. 
- Furthermore, cortex sees incoming initial placement requests matching a reservation and unlocks it's space for the project.
- Additional refactoring so the reservations operator commitments syncer handles the filtering of commitments to convert to a reservation
> Implement commitment-reservation exchange

- internal/extractor/plugins/shared/host_pinned_project_test.go
- internal/extractor/plugins/shared/host_utilization_test.go
- refactored `host_pinned_project` and `host_utilization` tests
- use unified test structure to avoid code duplication
> Clean up host_pinned_project and host_utilization tests

- helm/bundles/cortex-nova/alerts/nova.alerts.yaml
- Add alert for `cortex-nova-kpis` service down
- Dashboard show some gaps in the data of the last week
- Didn't notice that the kpi service was down
- Wouldn't make an alert for manila or cinder kpis since the service is not that important there
- Add alert for `cortex-nova-descheduler` down
> Add alerts for Cortex KPI service and Descheduler down states

- internal/extractor/plugins/shared/vm_host_residency.sql
- internal/extractor/plugins/vmware/vrops_hostsystem_resolver.sql
- internal/extractor/plugins/vmware/vrops_project_noisiness.sql
- internal/sync/openstack/nova/nova_api.go
- internal/sync/openstack/nova/nova_api_test.go
- internal/sync/openstack/nova/nova_sync.go
- internal/sync/openstack/nova/nova_sync_test.go
- internal/sync/openstack/nova/nova_types.go
Refactor nova syncer for migrations to fetch complete history + minor adjustment to comments and general clean up
> Refactor openstack migrations syncer
